# Triple store info

# Dydra
sparql-endpoint: http://pH9iszmNQWav1k0RZZYA@api.dydra.com/alphajuliet/network-rdf/sparql
rest-endpoint: http://pH9iszmNQWav1k0RZZYA@api.dydra.com/alphajuliet/network-rdf
repo-endpoint: http://pH9iszmNQWav1k0RZZYA@api.dydra.com/alphajuliet/network-rdf/statements
graph-uri: http://alphajuliet.com/ns/network-rdf

# 4store local copy
# sparql-endpoint: http://localhost:8000/sparql/
# rest-endpoint: http://localhost:8000/data/


